# Generated by Django 3.2.13 on 2024-10-18 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'managed': False},
        ),
    ]
