# Generated by Django 3.2.13 on 2024-10-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_alter_server_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='ssh_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
